version: 2.1
jobs:
    build-push-jupyter-datascience-notebook:
        machine:
            image: ubuntu-1604:201903-01
            resource_class: large
        steps:
            - checkout
            - run:
                name: docker login
                command: docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: build jupyter datascience image
                command: docker build -t colibridigital/jupyter-datascience-notebook jupyter-datascience-notebook/
            - run:
                name: tag image
                command: | 
                    docker tag colibridigital/jupyter-datascience-notebook colibridigital/jupyter-datascience-notebook:latest
                    docker tag colibridigital/jupyter-datascience-notebook colibridigital/jupyter-datascience-notebook:$CIRCLE_BUILD_NUM
            - run:
                name: push jupyter datascience image
                command: |
                    docker push colibridigital/jupyter-datascience-notebook:latest
                    docker push colibridigital/jupyter-datascience-notebook:$CIRCLE_BUILD_NUM

    build-push-jupyter-datascience-gpu-notebook:
        machine:
            image: ubuntu-1604:201903-01
            resource_class: large
        steps:
            - checkout
            - run:
                name: docker login
                command: docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: build jupyter datascience gpu image
                command: docker build -t colibridigital/jupyter-datascience-notebook:gpu jupyter-datascience-gpu-notebook/
            - run:
                name: tag image
                command: | 
                    docker tag colibridigital/jupyter-datascience-notebook:gpu  colibridigital/jupyter-datascience-notebook:gpu-$CIRCLE_BUILD_NUM
            - run:
                name: push jupyter datascience gpu image
                command: |
                    docker push colibridigital/jupyter-datascience-notebook:gpu
                    docker push colibridigital/jupyter-datascience-notebook:gpu-$CIRCLE_BUILD_NUM
                    
workflows:
    version: 2.1
    build-push-images:
        jobs:
        - build-push-jupyter-datascience-notebook:
            filters:
                branches:
                    only: master
        - build-push-jupyter-datascience-gpu-notebook:
            filters:
                branches:
                    only: master
    weekly:
        triggers:
        - schedule:
            cron: "0 1 * * 0"
            filters:
                branches:
                    only: master
        jobs:
        - build-push-jupyter-datascience-notebook
        - build-push-jupyter-datascience-gpu-notebook
    